INSERT INTO PRODUCT 
(PRODUCT_ID, PRODUCT_NAME, UNIT, UNITS_IN_STOCK, PRICE_PER_UNIT, CATEGORY, SUB_CATEGORY, RATING_BY_CUSTOMER)
VALUES
(1, 'Eggs', '12 pcs', 100, 99, 'Breakfast', 'Local', 5.00);


INSERT INTO PRODUCT 
(PRODUCT_ID, PRODUCT_NAME, UNIT, UNITS_IN_STOCK, PRICE_PER_UNIT, CATEGORY, SUB_CATEGORY, RATING_BY_CUSTOMER)
VALUES
(2, 'White Bread', '500 gm', 100, 75, 'Breakfast', 'Local', 4.3);