CREATE OR REPLACE PROCEDURE CONFIRM_CREDIT_CARD
(
	ONO 	IN 	INT,
	CID 	IN 	INT,
	UNAME 	IN 	VARCHAR,
	BNK 	IN 	VARCHAR,
	CTYPE 	IN 	VARCHAR,
	CNO 	IN 	VARCHAR
)
IS
BEGIN
	
	INSERT INTO CREDIT_CARD
	(ORDAR_NO, CUSTOMER_ID, USERNAME, BANK, CARD_TYPE, CARD_NO)
	VALUES
	(ONO, CID, UNAME, BNK, CTYPE, CNO);
	
	COMMIT;

END;
/
