CREATE OR REPLACE PROCEDURE UPDATE_CUSTOMER_PAYMENT_INFO
(
		CID				IN 		INT,
		USRNAME		IN 		VARCHAR,
		BNK 			IN 		VARCHAR,
		CRDTYPE 	IN 		VARCHAR,
		CRDNO 		IN 		VARCHAR,
		BKSPNO 		IN 		VARCHAR
)
IS

		CNT		INT;

BEGIN

		SELECT COUNT(*) INTO CNT FROM CUSTOMER_PAYMENT_INFO WHERE CUSTOMER_ID = CID;

		IF CNT > 0 THEN

				UPDATE CUSTOMER_PAYMENT_INFO
				SET 
							USERNAME = USRNAME,
							BANK = BNK,
							CARD_TYPE = CRDTYPE,
							CARD_NO = CRDNO,
							BKASH_PHONE_NO = BKSPNO
				WHERE
							CUSTOMER_ID = CID;

		ELSE
		
				INSERT INTO CUSTOMER_PAYMENT_INFO
				(CUSTOMER_ID, USERNAME, BANK, CARD_TYPE, CARD_NO, BKASH_PHONE_NO)
				VALUES
				(CID, USRNAME, BNK, CRDTYPE, CRDNO, BKSPNO);
		
		END IF;

		COMMIT;
					
END;
/