DROP PROCEDURE SAVE_PRODUCT_RATING;

CREATE OR REPLACE PROCEDURE UPDATE_PRODUCT_RATING
(
		PID 		IN 		INT,
		RT 			IN 		INT
)
IS
	
		CNT 		INT;

BEGIN

		SELECT COUNT(*) INTO CNT FROM PRODUCT_RATING WHERE PRODUCT_ID = PID;

		IF CNT > 0 THEN
				UPDATE PRODUCT_RATING
				SET 
						TOTAL_RATING = TOTAL_RATING + RT,
						TOTAL_CUSTOMER = TOTAL_CUSTOMER + 1
				WHERE 
						PRODUCT_ID = PID;
		ELSE
				INSERT INTO PRODUCT_RATING
				(PRODUCT_ID, TOTAL_RATING, TOTAL_CUSTOMER)
				VALUES
				(PID, RT, 1);
		END IF;
	
		COMMIT;
	
END;
/


