CREATE OR REPLACE PROCEDURE UPDATE_CUSTOMER_INFO
(
		CID 		IN 	INT,
		CNAME 	IN	VARCHAR,
		MAIL 		IN 	VARCHAR,
		PHN			IN	VARCHAR,
		SNO 		IN 	VARCHAR,
		HNO 		IN 	VARCHAR,
		ANO 		IN 	VARCHAR
)
IS

		CNT			INT;

BEGIN

	UPDATE	CUSTOMER
	SET 	
					CUSTOMER_NAME = CNAME,
					EMAIL = MAIL,
					STREET_NO = SNO,
					HOUSE_NO = HNO,
					APT_NO = ANO
	WHERE
					CUSTOMER_ID = CID;
					
	

	SELECT COUNT(*) INTO CNT FROM CUSTOMER_PHONE WHERE CUSTOMER_ID = CID;
	
	IF CNT > 0 THEN
			UPDATE	CUSTOMER_PHONE
			SET
							PHONE_NUMBER = PHN
			WHERE
							CUSTOMER_ID = CID;
	ELSE
			INSERT INTO CUSTOMER_PHONE
			(CUSTOMER_ID, PHONE_NUMBER)
			VALUES
			(CID, PHN);
	END IF;

	COMMIT;

END;
/