CREATE OR REPLACE FUNCTION GET_PRODUCT
(
		PID 	IN 		INT,
		T 		IN 		VARCHAR
)
RETURN VARCHAR
IS

		RET		VARCHAR(100);

BEGIN

		IF T = 'PRODUCT_NAME' THEN
				SELECT PRODUCT_NAME INTO RET FROM PRODUCT WHERE PRODUCT_ID = PID;
				
		ELSIF T = 'UNIT' THEN
				SELECT UNIT INTO RET FROM PRODUCT WHERE PRODUCT_ID = PID;
		
		ELSIF T = 'UNITS_IN_STOCK' THEN
				SELECT TO_CHAR(UNITS_IN_STOCK) INTO RET FROM PRODUCT WHERE PRODUCT_ID = PID;
		
		ELSIF T = 'PRICE_PER_UNIT' THEN
				SELECT TO_CHAR(PRICE_PER_UNIT) INTO RET FROM PRODUCT WHERE PRODUCT_ID = PID;
		
		ELSIF T = 'CATEGORY' THEN
				SELECT CATEGORY INTO RET FROM PRODUCT WHERE PRODUCT_ID = PID;
		
		ELSIF T = 'SUB_CATEGORY' THEN
				SELECT SUB_CATEGORY INTO RET FROM PRODUCT WHERE PRODUCT_ID = PID;
		
		ELSIF T = 'RATING_BY_CUSTOMER' THEN
				SELECT TO_CHAR(RATING_BY_CUSTOMER) INTO RET FROM PRODUCT WHERE PRODUCT_ID = PID;
		
		ELSIF T = 'PERCENT_DISCOUNT' THEN
				SELECT TO_CHAR(PERCENT_DISCOUNT) INTO RET FROM FLASH_SALE WHERE PRODUCT_ID = PID;
		
		END IF;
		
		RETURN RET;

EXCEPTION
		WHEN NO_DATA_FOUND THEN
				RETURN '';
		WHEN OTHERS THEN
				RETURN '';

END;
/