CREATE OR REPLACE FUNCTION GET_PRODUCT_PRICE ( PID IN INT )
RETURN INT IS
	RET INT;
BEGIN

	SELECT PRICE_PER_UNIT INTO RET FROM PRODUCT WHERE PRODUCT_ID = PID;
	RETURN RET;

EXCEPTION
	WHEN NO_DATA_FOUND THEN
		RETURN 0;
END;
/


-- SELECT GET_PRODUCT_PRICE(10) FROM CUSTOMER;