CREATE OR REPLACE FUNCTION GET_BKASH
(
	MAIL 	IN 	VARCHAR,
	ATT		IN	VARCHAR
) 
RETURN VARCHAR IS

	MY_ID 	INT;
	RET 	VARCHAR(100);

BEGIN

	SELECT CUSTOMER_ID INTO MY_ID FROM CUSTOMER WHERE EMAIL = MAIL;
	
	IF 		ATT = 'PHONE_NO'	THEN
		SELECT PHONE_NO INTO RET FROM BKASH WHERE CUSTOMER_ID = MY_ID;
	END IF;
	
	RETURN RET;

EXCEPTION

	WHEN NO_DATA_FOUND THEN
		RETURN '';
	WHEN OTHERS THEN
		RETURN '';

END;
/