CREATE OR REPLACE FUNCTION GET_CREDIT_CARD
(
	MAIL 	IN 	VARCHAR,
	ATT		IN	VARCHAR
) 
RETURN VARCHAR IS

	MY_ID 	INT;
	RET 	VARCHAR(100);

BEGIN

	SELECT CUSTOMER_ID INTO MY_ID FROM CUSTOMER WHERE EMAIL = MAIL;
	
	IF 		ATT = 'USERNAME' 	THEN
		SELECT USERNAME INTO RET FROM CREDIT_CARD WHERE CUSTOMER_ID = MY_ID;
	ELSIF 	ATT = 'BANK' 		THEN
		SELECT BANK INTO RET FROM CREDIT_CARD WHERE CUSTOMER_ID = MY_ID;
	ELSIF 	ATT = 'CARD_TYPE'	THEN
		SELECT CARD_TYPE INTO RET FROM CREDIT_CARD WHERE CUSTOMER_ID = MY_ID;
	ELSIF	ATT = 'CARD_NO'		THEN
		SELECT CARD_NO INTO RET FROM CREDIT_CARD WHERE CUSTOMER_ID = MY_ID;
	END IF;
	
	RETURN RET;

EXCEPTION

	WHEN NO_DATA_FOUND THEN
		RETURN NULL;
	WHEN OTHERS THEN
		RETURN NULL;

END;
/




