INSERT INTO PRODUCT 
(PRODUCT_ID, PRODUCT_NAME, UNIT, UNITS_IN_STOCK, PRICE_PER_UNIT, CATEGORY, SUB_CATEGORY, RATING_BY_CUSTOMER)
VALUES
(3, 'Malta', '2 kg', 100, 349, 'Fruit and Vegetable', 'Fruits', 0);


INSERT INTO PRODUCT 
(PRODUCT_ID, PRODUCT_NAME, UNIT, UNITS_IN_STOCK, PRICE_PER_UNIT, CATEGORY, SUB_CATEGORY, RATING_BY_CUSTOMER)
VALUES
(4, 'Banana', '12 pcs', 100, 59, 'Fruit and Vegetable', 'Fruits' ,0);


INSERT INTO PRODUCT 
(PRODUCT_ID, PRODUCT_NAME, UNIT, UNITS_IN_STOCK, PRICE_PER_UNIT, CATEGORY, SUB_CATEGORY, RATING_BY_CUSTOMER)
VALUES
(5, 'guava thai', '1 kg', 100, 89, 'Fruit and Vegetable', 'Fruits', 0);