INSERT INTO PRODUCT 
(PRODUCT_ID, PRODUCT_NAME, UNIT, UNITS_IN_STOCK, PRICE_PER_UNIT, CATEGORY, SUB_CATEGORY, RATING_BY_CUSTOMER)
VALUES
(6, 'Onion Red', '1 kg', 100, 59, 'Fruit and Vegetable' , 'Vegetables', 0);


INSERT INTO PRODUCT 
(PRODUCT_ID, PRODUCT_NAME, UNIT, UNITS_IN_STOCK, PRICE_PER_UNIT, CATEGORY, SUB_CATEGORY, RATING_BY_CUSTOMER)
VALUES
(7, 'Potato', '1 kg', 100, 52, 'Fruit and Vegetable', 'Vegetables', 0);

INSERT INTO PRODUCT 
(PRODUCT_ID, PRODUCT_NAME, UNIT, UNITS_IN_STOCK, PRICE_PER_UNIT, CATEGORY, SUB_CATEGORY, RATING_BY_CUSTOMER)
VALUES
(8, 'Tomato', '500 gm', 100, 159, 'Fruit and Vegetable', 'Vegetables', 0);



