CREATE OR REPLACE TRIGGER REDUCE_STOCK_ON_ORDER
BEFORE INSERT 
ON PRODUCTS_IN_ORDER
FOR EACH ROW

DECLARE

BEGIN

		UPDATE PRODUCT P
		SET P.UNITS_IN_STOCK = P.UNITS_IN_STOCK - :NEW.QUANTITY
		WHERE P.PRODUCT_ID = :NEW.PRODUCT_ID;

END;
/
