CREATE TABLE CUSTOMER
(
    CUSTOMER_ID     INT         	NOT NULL,
    CUSTOMER_NAME   VARCHAR(20) 	NOT NULL,
    STREET_NO       VARCHAR(20) 	NOT NULL, 
    HOUSE_NO        VARCHAR(20) 	NOT NULL,
    APT_NO          VARCHAR(20) 	NOT NULL,
    EMAIL           VARCHAR(20),
    CUSTOMER_CREDIT INT,
    PASSWORD        VARCHAR(20) 	NOT NULL,

    CONSTRAINT CUSTOMER_PK PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE CUSTOMER_PHONE
(
    CUSTOMER_ID     INT     		NOT NULL,
    PHONE_NUMBER    NUMBER(11)     	NOT NULL,
	
	CONSTRAINT CUSTOMER_PHONE_PK PRIMARY KEY (CUSTOMER_ID),
	CONSTRAINT CUSTOMER_PHONE_FK FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);


CREATE TABLE ORDAR
(
    ORDAR_NO    INT          NOT NULL,
    ORDAR_DATE  DATE         NOT NULL,
    ORDAR_TIME  TIMESTAMP    NOT NULL,

    CONSTRAINT ORDAR_PK PRIMARY KEY (ORDAR_NO)
);


CREATE TABLE MAKES
(
    ORDAR_NO    INT     NOT NULL,
    CUSTOMER_ID INT     NOT NULL,

    CONSTRAINT MAKES_PK PRIMARY KEY (ORDAR_NO)
);

CREATE TABLE PRODUCT
(
    PRODUCT_ID  		INT     		NOT NULL,
    PRODUCT_NAME 		VARCHAR(20)    	NOT NULL,
    UNIT        		VARCHAR(5)  	NOT NULL,
    UNITS_IN_STOCK  	NUMBER(10, 2),
    PRICE_PER_UNIT  	NUMBER(20, 2), 
    CATEGORY    		VARCHAR(20),
    RATING_BY_CUSTOMER  NUMBER(2, 2),

    CONSTRAINT PRODUCT_PK PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE CONTAINS
(
    ORDAR_NO    INT             NOT NULL,
    PRODUCT_ID  INT             NOT NULL,
    QUANTITY    NUMBER(10, 2)   NOT NULL,

    CONSTRAINT CONTAINS_PK PRIMARY KEY (ORDAR_NO, PRODUCT_ID, QUANTITY)
);

CREATE TABLE OFFER
(
    PRODUCT_ID          INT     NOT NULL,
    START_DATE          DATE,
    END_DATE            DATE,
    QUANTITY            NUMBER(10, 2),
    PERCENT_DISCOUNT    NUMBER(2),

    CONSTRAINT OFFER_PK PRIMARY KEY (PRODUCT_ID),
    CONSTRAINT OFFER_FK FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

CREATE TABLE FREE
(
    MAIN_PRODUCT_ID         INT     NOT NULL,
    FREE_PRODUCT_ID         INT     NOT NULL,
    START_DATE              DATE,
    END_DATE                DATE,
    MAIN_PRODUCT_QUANTITY   NUMBER(10, 2),
    FREE_PRODUCT_QUANTITY   NUMBER(10, 2)
);

CREATE TABLE RATES
(
    CUSTOMER_ID     INT     NOT NULL,
    PRODUCT_ID      INT     NOT NULL,
    RATING_NO       NUMBER(2, 2), 

    CONSTRAINT RATES_PK PRIMARY KEY (CUSTOMER_ID, PRODUCT_ID)
);

CREATE TABLE PAYMENT
(
    PAYMENT_ID      INT             NOT NULL,
    PAYMENT_DATE    DATE            NOT NULL,
    TOTAL_COST      NUMBER(10, 2)   NOT NULL,
    DUE             NUMBER(10, 2)   NOT NULL,

    CONSTRAINT PAYMENT_PK PRIMARY KEY (PAYMENT_ID)
);

CREATE TABLE BKASH
(
    PAYMENT_ID      INT             NOT NULL,
    TRANS_ID        VARCHAR(20)     NOT NULL,
    PHONE_NO        NUMBER(11)      NOT NULL,

    CONSTRAINT BKASH_PK PRIMARY KEY (PAYMENT_ID)
);

CREATE TABLE CREDIT_CARD
(
    PAYMENT_ID      INT             NOT NULL,
    USERNAME        VARCHAR(20)     NOT NULL,
    BANK            VARCHAR(10)     NOT NULL,
    CARD_TYPE       VARCHAR(10)     NOT NULL,
    CARD_NO         VARCHAR(20)     NOT NULL,

    CONSTRAINT CREDIT_CARD_PK PRIMARY KEY (PAYMENT_ID)
);

CREATE TABLE CASH_ON_DELIVERY
(
    PAYMENT_ID      INT             NOT NULL,
    PAID            NUMBER(10, 2)   NOT NULL,
    CHANGE          NUMBER(10, 2)   NOT NULL,

    CONSTRAINT CASH_ON_DELIVERY_PK PRIMARY KEY (PAYMENT_ID)
);

CREATE TABLE NEEDS
(
    ORDAR_NO        INT     NOT NULL,    
    PAYMENT_ID      INT     NOT NULL,
    CUSTOMER_POINTS INT,

    CONSTRAINT NEEDS_PK PRIMARY KEY (ORDAR_NO)
);

CREATE TABLE AGENT
(
    AGENT_ID        INT             NOT NULL,
    AGENT_NAME      VARCHAR(20)     NOT NULL,
    AGENT_PHONE_NO  NUMBER(11)      NOT NULL,
    DELIVERY_CHARGE NUMBER(3, 2)    NOT NULL,

    CONSTRAINT AGENT_PK PRIMARY KEY (AGENT_ID)
);

CREATE TABLE RECEIVES
(
    ORDAR_NO        INT     NOT NULL,
    AGENT_ID        INT     NOT NULL,

    CONSTRAINT RECEIVES_PK PRIMARY KEY (ORDAR_NO)
);
