INSERT INTO PRODUCT 
(PRODUCT_ID, PRODUCT_NAME, UNIT, UNITS_IN_STOCK, PRICE_PER_UNIT, CATEGORY, RATING_BY_CUSTOMER)
VALUES
(1, 'eggs', 'piece', 12, 10, 'breakfast', 5.00);

UPDATE PRODUCT 
SET UNIT = '12 pcs'
WHERE PRODUCT_ID = 1;

INSERT INTO PRODUCT 
(PRODUCT_ID, PRODUCT_NAME, UNIT, UNITS_IN_STOCK, PRICE_PER_UNIT, CATEGORY, RATING_BY_CUSTOMER)
VALUES
(2, 'white bread', '500 gm', 10, 75, 'breakfast', 4.3);

UPDATE PRODUCT 
SET PRICE_PER_UNIT = 99
WHERE PRODUCT_ID = 1;