DROP TABLE PRODUCT CASCADE CONSTRAINTS;


CREATE TABLE PRODUCT
(
    PRODUCT_ID  				INT     				NOT NULL,
    PRODUCT_NAME 				VARCHAR(50)    	NOT NULL,
    UNIT        				VARCHAR(20)  		NOT NULL,
    UNITS_IN_STOCK  		NUMBER(10, 2),
    PRICE_PER_UNIT  		NUMBER(20, 2), 
    CATEGORY    				VARCHAR(20) 		NOT NULL,
		SUB_CATEGORY 				VARCHAR(20) 		NOT NULL,
    RATING_BY_CUSTOMER  NUMBER(3, 2),

    CONSTRAINT PRODUCT_PK PRIMARY KEY (PRODUCT_ID)
);